server:
  port: 8080

spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/supermarket?useUnicode=true&characterEncoding=utf8&useSSL=false
    username: root
    password: 123456
    type: com.alibaba.druid.pool.DruidDataSource
#   下面为连接池的补充设置，应用到上面所有数据源中
#   初始化大小，最小，最大
    initialSize: 1
    minIdle: 3
    maxActive: 20
#   配置获取连接等待超时的时间
    maxWait: 60000
#   配置间隔多久才进行一次检测，检测需要关闭的空闲连接，单位是毫秒
    timeBetweenEvictionRunsMillis: 60000
#   配置一个连接在池中最小生存的时间，单位是毫秒
    minEvictableIdleTimeMillis: 30000
    validationQuery: select 'x'
    testWhileIdle: true
    testOnBorrow: false
    testOnReturn: false
#   打开PSCache，并且指定每个连接上PSCache的大小
    poolPreparedStatements: true
    maxPoolPreparedStatementPerConnectionSize: 20
#   配置监控统计拦截的filters，去掉后监控界面sql无法统计，'wall'用于防火墙
    filters: stat,wall,slf4j
#   通过connectProperties属性来打开mergeSql功能；慢SQL记录
    connectionProperties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=5000
#   合并多个DruidDataSource的监控数据
    useGlobalDataSourceStat: true
  redis:
    database: 1
    host: localhost
    pool:
        max-active: 8
        max-idle: 500
        max-wait: -1
        min-idle: 0
    port: 6379
    timeout: 0


  thymeleaf:
    mode: HTML5
    encoding: UTF-8
    content-type: text/html
    cache: false
  aop:
    proxy-target-class: true
  http:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB

#  resources:
#    static-locations: /static


mybatis:
  mapper-locations: classpath:com/lgren/mapper/*.xml
pagehelper:
  helper-dialect: mysql
  reasonable: true
  support-methods-arguments: true
  params: count=countSql


#自己设置的一些配置
com:
  lgren:
    uploadPath: /fileUpload/
    downloadPath: /fileDownload/